config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :abilities
  resources :skills
  resources :races
  devise_for :users
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/race.rb
class Race < ApplicationRecord
    has_many :characters
    validates :name, presence: true
    validates :description, presence: true
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Rasa utworzona pomyślnie.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Rasa zmieniona pomyślnie.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Rasa usunięta pomyślnie.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name, :description)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_for(race) do |f| %>
  <% if race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nazwa" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Opis" %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Zatwierdź", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Edycja rasy</h1>

<%= render 'form', race: @race %>

<%= link_to 'Wyświetl', @race %> |
<%= link_to 'Wstecz', races_path %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rasy</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Opis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>
        <td><%= race.description %></td>
        <td><%= link_to 'Wyświetl', race %></td>
        <td><%= link_to 'Edytuj', edit_race_path(race) %></td>
        <td><%= link_to 'Usuń', race, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
 
</table>
<%= will_paginate @races, renderer: BootstrapPagination::Rails, :previous_label => 'Poprzednie', :next_label => 'Następne'  %>
<br>
<%= link_to 'Nowa rasa', new_race_path %>

app/views/races/new.html.erb
<h1>Nowa rasa</h1>

<%= simple_form_for @race do |f| %>
  <%= f.input :name, label: 'Nazwa', placeholder: 'Tutaj wpisz nazwe rasy', allow_blank: false %>
  <%= f.input :description, label: 'Opis', placeholder: 'Tutaj wpisz krótki opis', allow_blank: false %>
  <%= f.button :submit, 'Stwórz' %>
<% end %>

<%= link_to 'Wstecz', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @race.name %>
</p>

<p>
  <strong>Opis:</strong>
  <%= @race.description %>
</p>

<%= link_to 'Edytuj', edit_race_path(@race) %> |
<%= link_to 'Wstecz', races_path %>