config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :abilities
  resources :skills
  resources :races
  devise_for :users
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/character.rb
class Character < ApplicationRecord
    belongs_to :race
    validates :name, presence: true
    validates :age, presence: true
    validates :sex, presence: true
    validates :eyecolor, presence: true
    validates :haircolor, presence: true
    validates :birthsign, presence: true
    validates :placeofbirth, presence: true
    validates :weight, presence: true
    validates :height, presence: true
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
    @races = Race.all()
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
    @races = Race.all()
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)
    @char_race = Race.find(@character.race_id)
    set_main_parameters
    set_secondary_parameters
    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Postać utworzona.' }
        format.json { render :show, status: :created, location: @character }
      else
        @races = Race.all()
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Postać zaktualizowana.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Postać usunięta' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :age, :sex, :eyecolor, :haircolor, :birthsign, :placeofbirth, :specialmarks, :weight, :height, :experience, :ww, :us, :k, :odp, :zr, :intelligence, :sw, :ogd, :a, :hp, :s, :wt, :sz, :mag, :po, :pp, :race_id)
    end
    
    def set_main_parameters
      case @char_race.name
      when "Krasnolud"
        set_parameters_krasnolud
      when "Elf"
        set_parameters_elf
      when "Niziołek"
        set_parameters_niziolek
      else
        set_parameters_human_and_default
      end
    end
    
    def set_secondary_parameters
      @character.s = @character.k / 10
      @character.wt = @character.odp / 10
      @character.mag = 0
      @character.po = 0
      @character.pp = roll(2,1) + 1
    end
    
    def set_parameters_krasnolud
      @character.ww = roll(10,2) + 30
      @character.us = roll(10,2) + 20
      @character.k = roll(10,2) + 20
      @character.odp = roll(10,2) + 30
      @character.zr = roll(10,2) + 10
      @character.intelligence = roll(10,2) + 20
      @character.sw = roll(10,2) + 20
      @character.ogd = roll(10,2) + 10
      @character.a = 1
      @character.hp = roll(4,1) + 10
      @character.sz = 3
    end
    
    def set_parameters_elf
      @character.ww = roll(10,2) + 20
      @character.us = roll(10,2) + 30
      @character.k = roll(10,2) + 20
      @character.odp = roll(10,2) + 20
      @character.zr = roll(10,2) + 30
      @character.intelligence = roll(10,2) + 20
      @character.sw = roll(10,2) + 20
      @character.ogd = roll(10,2) + 20
      @character.a = 1
      @character.hp = roll(4,1) + 8
      @character.sz = 5
    end
    
    def set_parameters_niziolek
      @character.ww = roll(10,2) + 10
      @character.us = roll(10,2) + 30
      @character.k = roll(10,2) + 10
      @character.odp = roll(10,2) + 10
      @character.zr = roll(10,2) + 30
      @character.intelligence = roll(10,2) + 20
      @character.sw = roll(10,2) + 20
      @character.ogd = roll(10,2) + 30
      @character.a = 1
      @character.hp = roll(4,1) + 7
      @character.sz = 4
    end
    
    def set_parameters_human_and_default
      @character.ww = roll(10,2) + 20
      @character.us = roll(10,2) + 20
      @character.k = roll(10,2) + 20
      @character.odp = roll(10,2) + 20
      @character.zr = roll(10,2) + 20
      @character.intelligence = roll(10,2) + 20
      @character.sw = roll(10,2) + 20
      @character.ogd = roll(10,2) + 20
      @character.a = 1
      @character.hp = roll(4,1) + 9
      @character.sz = 4
    end
    
    def roll(sides, number=1)
      roll_array = []
      number.times do
        roll_value = rand(sides) + 1
        roll_array << roll_value
      end
      total = 0
      roll_array.each do |roll|
        new_total = total + roll
        total = new_total
      end
      total
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(character) do |f| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Imię" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :race, "Rasa" %>
    <%= f.collection_select :race_id, @races, :id, :name, {}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :age, "Wiek" %>
    <%= f.text_field :age, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :sex, "Płeć" %>
    <%= f.text_field :sex, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :weight, "Waga" %>
    <%= f.text_field :weight, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :height, "Wzrost" %>
    <%= f.text_field :height, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :eyecolor, "Kolor oczu" %>
    <%= f.text_field :eyecolor, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :haircolor, "Kolor włosów" %>
    <%= f.text_field :haircolor, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :birthsign, "Znak gwiezdny" %>
    <%= f.text_field :birthsign, class: 'form-control' %>
  </div>
  
   <div class="form-group">
    <%= f.label :placeofbirth, "Pochodznie" %>
    <%= f.text_field :placeofbirth, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :specialmarks, "Znaki specjalne" %>
    <%= f.text_field :specialmarks, class: 'form-control' %>
  </div>
  
  <div class="actions">
    <%= f.submit "Zatwierdź", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Edycja postaci</h1>

<%= render 'form', character: @character %>

<%= link_to 'Pokaż', @character %> |
<%= link_to 'Wróć', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Postacie</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Imię</th>
      <th>Rasa</th>
      <th>Wiek</th>
      <th>Płeć</th>
      <th>Kolor oczu</th>
      <th>Kolor włosów</th>
      <th>Znak gwiezdny</th>
      <th>Pochodzenie</th>
      <th>Znaki specjalne</th>
      <th>Waga</th>
      <th>Wzrost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.race.name %></td>
        <td><%= character.age %></td>
        <td><%= character.sex %></td>
        <td><%= character.eyecolor %></td>
        <td><%= character.haircolor %></td>
        <td><%= character.birthsign %></td>
        <td><%= character.placeofbirth %></td>
        <td><%= character.specialmarks %></td>
        <td><%= character.weight %></td>
        <td><%= character.height %></td>
        <td><%= link_to 'Wyświetl', character %></td>
        <td><%= link_to 'Edytuj', edit_character_path(character) %></td>
        <td><%= link_to 'Usuń', character, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nowa postać', new_character_path %>

app/views/characters/new.html.erb
<h1>Nowa postać</h1>

<%= render 'form', character: @character %>

<%= link_to 'Wróć', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Imię:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Wiek:</strong>
  <%= @character.age %>
</p>

<p>
  <strong>Płeć:</strong>
  <%= @character.sex %>
</p>

<p>
  <strong>Kolor oczu:</strong>
  <%= @character.eyecolor %>
</p>

<p>
  <strong>Kolor włosów:</strong>
  <%= @character.haircolor %>
</p>

<p>
  <strong>Znak gwiezdny:</strong>
  <%= @character.birthsign %>
</p>

<p>
  <strong>Pochodzenie:</strong>
  <%= @character.placeofbirth %>
</p>

<p>
  <strong>Znaki specjalne:</strong>
  <%= @character.specialmarks %>
</p>

<p>
  <strong>Waga:</strong>
  <%= @character.weight %>
</p>

<p>
  <strong>Wzrost:</strong>
  <%= @character.height %>
</p>

<p>
  <strong>Doświadczenie:</strong>
  <%= @character.experience %>
</p>

<p>
  <strong>Walka wręcz:</strong>
  <%= @character.ww %>
</p>

<p>
  <strong>Umiejętności strzeleckie:</strong>
  <%= @character.us %>
</p>

<p>
  <strong>Krzepa:</strong>
  <%= @character.k %>
</p>

<p>
  <strong>Odporność:</strong>
  <%= @character.odp %>
</p>

<p>
  <strong>Zręczność:</strong>
  <%= @character.zr %>
</p>

<p>
  <strong>Inteligencja:</strong>
  <%= @character.intelligence %>
</p>

<p>
  <strong>Siła woli:</strong>
  <%= @character.sw %>
</p>

<p>
  <strong>Ogłada:</strong>
  <%= @character.ogd %>
</p>

<p>
  <strong>Ataki:</strong>
  <%= @character.a %>
</p>

<p>
  <strong>Zdrowie:</strong>
  <%= @character.hp %>
</p>

<p>
  <strong>Siła:</strong>
  <%= @character.s %>
</p>

<p>
  <strong>Wytrzymałość:</strong>
  <%= @character.wt %>
</p>

<p>
  <strong>Szybkość:</strong>
  <%= @character.sz %>
</p>

<p>
  <strong>Magia:</strong>
  <%= @character.mag %>
</p>

<p>
  <strong>Punkty obłędu:</strong>
  <%= @character.po %>
</p>

<p>
  <strong>Punkty postaci:</strong>
  <%= @character.pp %>
</p>

<%= link_to 'Edytuj', edit_character_path(@character) %> |
<%= link_to 'Wróć', characters_path %>