config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :abilities
  resources :skills
  resources :races
  devise_for :users
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability < ApplicationRecord
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  before_action :set_ability, only: [:show, :edit, :update, :destroy]

  # GET /abilities
  # GET /abilities.json
  def index
    @abilities = Ability.all
  end

  # GET /abilities/1
  # GET /abilities/1.json
  def show
  end

  # GET /abilities/new
  def new
    @ability = Ability.new
  end

  # GET /abilities/1/edit
  def edit
  end

  # POST /abilities
  # POST /abilities.json
  def create
    @ability = Ability.new(ability_params)

    respond_to do |format|
      if @ability.save
        format.html { redirect_to @ability, notice: 'Ability was successfully created.' }
        format.json { render :show, status: :created, location: @ability }
      else
        format.html { render :new }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abilities/1
  # PATCH/PUT /abilities/1.json
  def update
    respond_to do |format|
      if @ability.update(ability_params)
        format.html { redirect_to @ability, notice: 'Ability was successfully updated.' }
        format.json { render :show, status: :ok, location: @ability }
      else
        format.html { render :edit }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abilities/1
  # DELETE /abilities/1.json
  def destroy
    @ability.destroy
    respond_to do |format|
      format.html { redirect_to abilities_url, notice: 'Ability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ability
      @ability = Ability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ability_params
      params.require(:ability).permit(:name, :description)
    end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/views/abilities/_form.html.erb
<%= simple_form_for(@ability) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/abilities/edit.html.erb
<h1>Editing Ability</h1>

<%= render 'form', ability: @ability %>

<%= link_to 'Show', @ability %> |
<%= link_to 'Back', abilities_path %>

app/views/abilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zdolności</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abilities.each do |ability| %>
      <tr>
        <td><%= ability.name %></td>
        <td><%= ability.description %></td>
        <td><%= link_to 'Wyświetl', ability %></td>
        <td><%= link_to 'Edytuj', edit_ability_path(ability) %></td>
        <td><%= link_to 'Usuń', ability, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nowa zdolność', new_ability_path %>

app/views/abilities/new.html.erb
<h1>New Ability</h1>

<%= render 'form', ability: @ability %>

<%= link_to 'Back', abilities_path %>

app/views/abilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ability.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ability.description %>
</p>

<%= link_to 'Edit', edit_ability_path(@ability) %> |
<%= link_to 'Back', abilities_path %>