config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :abilities
  resources :skills
  resources :races
  devise_for :users
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Kreator postaci', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar">
    <!--<li><%= link_to 'Strona główna', root_path %></li>-->
        <li><%= link_to 'O mnie', home_about_path %></li>
        <li><%= link_to 'Rasy', races_path %></li>
    <!--<li><%= link_to 'Umiejętności', skills_path %></li>-->
    <!-- <li><%= link_to 'Zdolności', abilities_path %></li>-->
        <li><%= link_to 'Postacie', characters_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Edytuj profil', edit_user_registration_path %></li>
          <li><%= link_to 'Wyloguj', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Zaloguj', new_user_session_path %></li>
          <li><%= link_to 'Zarejestruj', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kreator postaci</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      
      <%= yield %>
    </div>
  
  </body>

</html>